# SPDX-FileCopyrightText: Simon Schneegans <code@simonschneegans.de>
# SPDX-License-Identifier: CC0-1.0

name: Test Deploy

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  linux:
    name: Linux
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: |
          sudo apt install libx11-dev libxtst-dev libwayland-dev libxkbcommon-dev
          npm install
      - name: Fix Permissions
        # Workaround for https://github.com/electron/electron/issues/17972
        run: |
          sudo chmod 4755 node_modules/electron/dist/chrome-sandbox
          sudo chown root node_modules/electron/dist/chrome-sandbox
      - name: Create Packages
        run: |
          npm run make
      - name: Create AppImage
        run: |
          tools/make-app-image.sh
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: out/make/**/*
          retention-days: 7

  windows:
    name: Windows
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        # For some reason cmake.js sometimes skips the build step in CI on Windows in this
        # case. So we install and execute cmake.js manually.
        run: |
          npm install cmake-js -g
          npx cmake-js install
          npm install
      - name: Create Release
        run: |
          npm run make
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-windows-2022
          path: |
            out/make/zip/win32/x64/*
            out/make/squirrel.windows/x64/*.exe
          retention-days: 7

  macos:
    name: macOS
    strategy:
      matrix:
        os: [macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      # https://github.com/electron/forge/issues/2807
      - run: python3 -m pip install setuptools --break-system-packages
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: |
          npm install
          npm install appdmg
      - name: Add macOS certificates
        if: ${{ ! github.event.pull_request.head.repo.fork && github.actor != 'dependabot[bot]' }}
        env:
          OSX_CERTIFICATE: ${{ secrets.OSX_CERTIFICATE }}
          OSX_CERTIFICATE_PASSWORD: ${{ secrets.OSX_CERTIFICATE_PASSWORD }}
        run: |
          .github/osx_certificates.sh
      - name: Create Release
        env:
          KANDO_OSX_SIGN: ${{ ! github.event.pull_request.head.repo.fork && github.actor != 'dependabot[bot]' }}
          KANDO_OSX_NOTARIZE: ${{ ! github.event.pull_request.head.repo.fork && github.actor != 'dependabot[bot]' }}
          OSX_APP_SPECIFIC_ID: ${{ secrets.OSX_APP_SPECIFIC_ID }}
          OSX_APP_SPECIFIC_PASSWORD: ${{ secrets.OSX_APP_SPECIFIC_PASSWORD }}
          OSX_TEAM_ID: ${{ secrets.OSX_TEAM_ID }}
        run: |
          npm run make
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: |
            out/make/*.dmg
            out/make/zip/darwin/**/*.zip
          retention-days: 7
